Initial commit
mydeadvictoria/spring-integration-demo-task pull request #1
Opened 2020-11-11 06:18 UTC by mydeadvictoria

2020-11-11 07:24 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/service/CatsApiService.java
> +    private final WebClient webClient;
Чому ти використав реактивий WebClient для доступу до API?

2020-11-11 07:24 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/configuration/AppConfig.java
> +    public WebClient webClient() {
WebClient is a reactive class to work with reactive API. Is it a standard WebClient for working with Spring Integration or something else?

2020-11-11 07:24 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/configuration/integration/CatsIntegration.java
> +        return IntegrationFlows.from(catsApiService::getRandomCatPic, e -> e.poller(p -> p.fixedRate(3500)))
Lets, drop this flow into beans, so we will see an interesting picture.

2020-11-11 07:24 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/configuration/integration/CatsIntegration.java
> +                .transform(CatsApiResponse.class, resp -> CatPicture.builder()
Can you remove `CatPicture` class and strt using json object without converting into java code?

2020-11-11 07:24 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/configuration/integration/CatsIntegration.java
> +                .handle(CatPicture.class, (cat, h) -> catsApiService.downloadPicture(cat.getOrigUrl()))
Remove the logic of download a picture and save it to a folder. Instead of it make transformation of object from json to XML and save the result into DB

2020-11-11 07:24 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/configuration/integration/CatsIntegration.java
> +                .handle(Jpa.updatingGateway(entityManagerFactory)
Start using MongoDB instead of MySQL to save data.

2020-11-11 07:24 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/db/entity/CatPicture.java
> +public class CatPicture {
Remove it

2020-11-11 07:24 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/db/repository/CatPictureRepository.java
> +public interface CatPictureRepository extends CrudRepository<CatPicture, Integer> {
Remove it too

2020-11-11 23:45 UTC, mydeadvictoria commented on src/main/java/com/example/springintegrationdemo/service/CatsApiService.java
> +    private final WebClient webClient;
RestTemplate в скорому часi deprecated, треба вiдвикати. Та i я ранiше вже юзав WebClient.

2020-11-11 23:48 UTC, mydeadvictoria commented on src/main/java/com/example/springintegrationdemo/configuration/AppConfig.java
> +    public WebClient webClient() {
It isn't. Indeed, SI doesn't care as it knows nothing about it. This bean is used by my own services only.

2020-11-23 07:35 UTC, koropatva requested changes

2020-11-23 07:35 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/mapper/JsonDataMapper.java
> +    private String mkArrayIdx(String key, int index) {
You don't use this method

2020-11-23 07:35 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/mapper/DataMapper.java
> +public interface DataMapper<T, S> {
What is a reason on this interface?

2020-11-23 07:36 UTC, koropatva requested changes

2020-11-23 07:36 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/integration/JsonMappingInt.java
> +        inputNode = jsonResourceLoader.loadObject(jsonFileName);
Rewrite JsonResourceLoader and YamlResourceLoader using Factory pettern

2020-11-24 09:57 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/util/ObjectNodeFactory.java
> +    public ObjectNode fromXml(String xmlContent) {
It doesn't make sense to move a call of the method into a separate method

2020-11-24 09:58 UTC, merged