Introduce SpEL support
mydeadvictoria/spring-integration-demo-task pull request #3
Opened 2020-11-25 08:10 UTC by mydeadvictoria

2020-11-25 08:14 UTC, koropatva requested changes

2020-11-25 08:14 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/mapper/JsonDataMapper.java
> +                String value = exprParser.parseExpression(schemeRoot.asText())
Make a separate service, move this logic there and call this service from here to fetch value

2020-11-26 13:43 UTC, koropatva requested changes

2020-11-26 13:43 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/helper/InlinedExpressionResolver.java
> +            Pattern.compile("\\(payload\\..* map \\{.+\\}\\)", Pattern.DOTALL).asMatchPredicate();
Move `payload` into static field and use it everywhere

2020-11-26 13:43 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/helper/InlinedExpressionResolver.java
> +        if (VALID_VALUE_EXPRESSION_PREDICATE.test(expression)) {
Rewrite it with patterns: create interface and for each if -> reaslization with two methods: one check method to check your condition and another to run inner code

2020-11-26 14:36 UTC, koropatva requested changes

2020-11-26 14:36 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/expression/ArrayExpressionResolver.java
> +                elementData.put("$$", idx);
Move "$$" and "$" into static fields on the same file where `payload`

2020-11-26 14:36 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/expression/ArrayExpressionResolver.java
> +            Pattern.compile("\\(payload\\..* map \\{.+\\}\\)", Pattern.DOTALL).asMatchPredicate();
Move `payload` into separate field

2020-11-26 14:36 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/expression/ArrayExpressionResolver.java
> +            Pattern.compile("\\(payload\\.(.+) map (\\{.+\\})\\)", Pattern.DOTALL);
and from here

2020-11-26 14:36 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/expression/ArrayExpressionResolver.java
> +            log.info("elementScheme: {}", elementScheme.toPrettyString());
use debug log on all core

2020-11-26 14:36 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/expression/ArrayValueExpressionResolver.java
> +        return expression.startsWith("$$") || expression.startsWith("$.");
move to static fields

2020-11-26 14:36 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/expression/ArrayValueExpressionResolver.java
> +        if (expression.equals("$$") && data.containsKey("$$")) {
here too

2020-11-26 14:36 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/expression/ValueExpressionResolver.java
> +    private static final String VALUE_PREFIX = "payload.";
use simple `payload` and rewrite this string in all files

2020-11-26 14:36 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/expression/ValueExpressionResolver.java
> +        if (value != null) {
if (value != null) {
            return new TextNode(value);
        }
        return null;

2020-11-26 14:36 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/expression/ArrayExpressionResolver.java
> +    @Autowired
maybe it should be `final`?

2020-11-26 14:36 UTC, koropatva commented on src/main/java/com/example/springintegrationdemo/engine/expression/ArrayExpressionResolver.java
> +    public boolean canResolve(String expression) {
rename to `check`

2020-11-26 14:38 UTC, mydeadvictoria commented on src/main/java/com/example/springintegrationdemo/engine/expression/ArrayExpressionResolver.java
> +    @Autowired
No, in case of `final` we get a dependency cycle.

2020-11-26 14:43 UTC, koropatva approved these changes

2020-11-30 10:24 UTC, merged